version: '3'

services:

   postgis:
    image: mdillon/postgis
    ports:
       - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
#      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data

   gisextras:
     build: ./gisextras
    
   geoserver:
     build: ./geoserver
     ports:
       - "8080:8080"



