version: '3'

services:

   postgis:
    image: mdillon/postgis
    ports:
       - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

       
#   geoserver:
#     image: kartoza/geoserver
#     ports:
#       - "8080:8080"